# RBEL-CRM: registers a Windows scheduled task that runs the Laravel scheduler every minute,
# so enabled Automations (birthday greetings, payment reminders) send by themselves,
# also after a restart. Runs for the current user while logged on, hidden (no window).
#
#   Install:    powershell -ExecutionPolicy Bypass -File install-scheduler.ps1
#   Uninstall:  powershell -ExecutionPolicy Bypass -File install-scheduler.ps1 -Uninstall
param([switch]$Uninstall)

$ErrorActionPreference = 'Stop'
$taskName = 'RBEL-CRM Demo Scheduler'
$root = $PSScriptRoot

if ($Uninstall) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
    Remove-Item (Join-Path $root 'run-scheduler.vbs') -ErrorAction SilentlyContinue
    Write-Output "Removed scheduled task '$taskName'."
    return
}

$php = (Get-Command php -ErrorAction Stop).Source

# Hidden launcher: wscript runs the command with no console window every minute.
$launcher = Join-Path $root 'run-scheduler.vbs'
$cmd = "cmd /c cd /d ""$root"" && ""$php"" artisan schedule:run >> storage\logs\scheduler.log 2>&1"
# VBScript escapes a quote inside a string by doubling it; build the line by concatenation
# so PowerShell's own quote handling cannot collapse those doubled quotes.
$vbsLine = 'CreateObject("WScript.Shell").Run "' + $cmd.Replace('"', '""') + '", 0, False'
Set-Content -Path $launcher -Encoding ASCII -Value @(
    "' Generated by install-scheduler.ps1: runs the RBEL-CRM scheduler once, hidden.",
    $vbsLine
)

$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "//B //NoLogo ""$launcher""" -WorkingDirectory $root
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date -RepetitionInterval (New-TimeSpan -Minutes 1)
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 10)
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal `
    -Description 'Runs php artisan schedule:run every minute for RBEL-CRM automations (birthday greetings, payment reminders).' -Force | Out-Null

Start-ScheduledTask -TaskName $taskName
Write-Output "Installed scheduled task '$taskName' (every minute, hidden). PHP: $php"
Write-Output "Log: $(Join-Path $root 'storage\logs\scheduler.log')"
